import = [ "/usr/lib/node_modules/alacritty-themes/themes/Kitty.toml" ]

[font]
size = 11

[font.normal]
family = "EnvyCodeR"
style = "Regular"

[scrolling]
history = 10_000

[window]
opacity = 0.95
title = "Alacritty"

[colors.primary]
background = '#0F1419'
